name: Hello World Training Workflow

on:
  workflow_dispatch:

jobs:
  cow:
    name: Cowsays
    runs-on: ubuntu-latest
    steps:
      - name: Ship it
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: "ship ship ship!"
          color: "red"
  greet:
    needs: cow
    env:
      MY_ENV: "John Doe"
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        echo "Hello $MY_ENV"
        echo "Hello $GITHUB_ACTOR"
